### ISSUE TITLE
Server doesnt start so the bot cant oauth 

### ISSUE THREAD

**Issue by AlixeAtTwitch** [Juraji/Biliomi#2]
Server doesnt start so the bot cant oauth screen shot below
![img](http://alixe.pro/share/img/chrome_142321549j040218.png)

**Comment by Juraji** [comment]
Okay, took some serious debugging and headscratching... 
[v3.18.2](https://github.com/Juraji/Biliomi/releases/tag/v3.18.2) fixes this problem.

For anyone interested:
During development within the IDE java resource files can be fetched with `SomeClass.class.getResource(...)` without problems. But when running as a JAR this throws an exception because the resource is now within a compressed file.
The solution is to use `SomeClass.class.getResourceAsStream(...)`.
